export default {
  CHARGE_STATUS_WAITING: 'waiting',
  CHARGE_STATUS_CREATED: 'created',
  CHARGE_STATUS_PAID: 'paid',
  CHARGE_STATUS_UNPAID: 'unpaid',
  PAYMENT_STATUS_APPROVED: 'approved',
  PAYMENT_STATUS_REFUSED: 'refused',
  MAXIMUM_PROCESSING_ATTEMPTS: 3
}
